### ISSUE TITLE
Place Entity 기능 개발

### ISSUE THREAD

**Issue by GomDue** [PBL-SHINHODONG/back-end#1]
---
name: Issue Template
about: Issue template for PBL projects
title: Place Entity 기능 개발
labels: feat1
assignees: GomDue
---

## Description
> place entity에 대한 기능 개발
## To-Do
- [x] place id를 통한 place 정보 반환
- [x] place name을 통한 place 정보 반환
- [x] place category를 통한 place 정보 반환
- [x] place x, y 좌표 반환
- [x] place 정렬 : 이름, 카테고리, 별점, 리뷰 수
- [x] place 필터링 : 카테고리, 별점, 리뷰 수

## Reference
