### ISSUE TITLE
User Entity 기능 개발

### ISSUE THREAD

**Issue by GomDue** [PBL-SHINHODONG/back-end#9]
---
name: Issue Template
about: Issue template for PBL projects
title: User Entity 기능 개발
labels: feat2
assignees: GomDue
---

## Description
> user entity에 대한 기능 개발
## To-Do
- [x] user id를 통한 user 정보 반환
- [x] user 로그인 기능
- [x] user 회원가입 기능
- [x] user 삭제 기능
- [x] user가 방문했던 place 반환

## Reference
